site_url: http://localhost:3000
logo_url: /icon.png
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
local_backend:
  url: http://localhost:8081/api/v1
media_folder: static/img
public_folder: /img
collections:
  - label: Site settings
    name: site
    files:
      - label: Site Data
        name: sitedata
        file: content/sitedata.json
        format: json
        editor:
          preview: false
        media_folder: '../static'
        public_folder: '/'
        fields:
          - label: Site Name
            name: name
            widget: string
            hint: This is used for the site title
          - label: Site Description
            name: description
            widget: string
            hint: This is used as descriptive text for links that link to this site
          - label: Site Language
            name: lang
            widget: string
            pattern:
              - ^[a-z]{2}([-])?([A-Za-z]{2})?$
              - Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")
          - label: Site Email
            name: email
            widget: string
            required: false
          - label: Social Networks
            name: networks
            widget: list
            required: false
            summary: "{{fields.name}}"
            fields:
              - label: Name
                name: name
                widget: string
                required: true
              - label: Url
                name: url
                widget: string
                required: true
              - label: Icon
                name: icon
                widget: image
                required: false
              - label: Handle
                name: handle
                widget: string
                required: true
          - label: Favicon
            name: favicon
            widget: file
            allow_multiple: false
            required: false
          - label: Tags
            name: tags
            widget: list
            allow_add: true
            default:
              - news
      - label: Cms Config
        name: cmsconfig
        file: static/admin/config.yml
        format: yml
        editor:
          preview: false
        fields:
          - label: Site Url
            name: site_url
            widget: string
            hint: This is used for the site domain or url, example http://localhost:3000
  - label: Pages
    label_singular: Page
    name: pages
    folder: content/pages
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Cover Image
        name: cover
        widget: image
        required: false
        allow_multiple: false
      - label: Description
        name: description
        widget: string
      - label: Body
        name: body
        widget: markdown
